### PR TITLE
encapsulate result class from swift

### PR DESCRIPTION
**Pull request by JesusMcCloud**
Does this help in any way?

* what about the hacks and casts from swift? can they be removed now?
* what about crashes on swift?

### CODE REVIEW

**Comment by nodh** [comment]
Function

```Swift
func funWithKotlin() -> KmmResult<NSString> {
    if 2 != 3 {
        return KmmResultKt.failure(error: KotlinThrowable(message: "error!"))
    } else {
        return KmmResultKt.success(value: "works!")
    }
}
```

gives errors

```
Cannot convert return expression of type 'KmmResult<AnyObject>' to return type 'KmmResult<NSString>'
```

and

```
Cannot convert return expression of type 'KmmResult<AnyObject>' to return type 'KmmResult<NSString>'
```

**Comment by JesusMcCloud** [comment]
so the same issues as before…

**Comment by nodh** [comment]
Not exactly the same IIRC, because the compiler error is now the same for both, the failure and success case.

**Comment by nodh** [comment]
Now this code builds:

```
func funWithKotlin() -> KmmResult<NSString> {
    if 2 != 3 {
        return KmmResult(failure: KotlinThrowable(message: "error!"))
    } else {
        return KmmResult(value: "works!")
    }
}
```

**Review by nodh — APPROVED** [review]
well done!

**Pull request merged**
